# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5366144371a2348f0b701bab53bcbf60fbdfd41cf93a118604721aa9888e7ba548f97ee3dd309ecc8fe3cac66d0bb989d2055e66b62427320268e6f27ac223b

test:
  secret_key_base: bd93d7bf1d86d66038166f104fe45b5a7ab410e8764c837d885b7bbabd51185b648d75eb29efb880af1b29b8ce8038c7567344271489060f51c8606013fba960

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
